# Generated by Django 3.2.5 on 2021-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Required field from models', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile'),
        ),
    ]
